tasks:
  - init: cmake .

vscode:
  extensions:
    - bbenoist.doxygen
    - cschlosser.doxdocgen
    - twxs.cmake
    - ms-vscode.cmake-tools
    - jacqueslucke.gcov-viewer
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
