/*****************************************************************//**
 * \file   messaging.h
 * \brief  
 * 
 * \author kason
 * \date   October 2021
 *********************************************************************/

#ifndef NETWORK_MESSAGES
#define NETWORK_MESSAGES

#include <cstring>
#include <vector>

/** A byte to send over the network. */
typedef unsigned char byte;

/**
 * List of network messages
 */
enum class MESSAGES : byte
{
	/** See Node_Messages::NODE_HELLO */
	NODE_HELLO,
	/** See Node_Messages::NODE_ACK */
	NODE_ACK,
	NODE_GOODBYE,
	/** Undefined message. */
	UNDEFINED = 255
};

/**
 * Header for message packets
 * |         |      |          |
 * |:-------:|:----:|:--------:|
 * |  01-08  |09-16 |   17-24  |
 * |pkt start|msg id|pkt length|
 */
struct MESSAGE_HEADER 
{ 
	/** Beginning bit for the message */
	byte message_start = 0x65; 
	/** Which message is being sent */
	MESSAGES message_id = MESSAGES::UNDEFINED; 
	/** How long the message is. Starts as the size of the header and footer. */
	byte length = 6; 
	/**
	* Boil the MESSAGE_HEADER down to an array of bytes that slapped at the beginning of a MESSAGE and sent across the network. 
	* It is mostly metadata about the message being sent.
	*
	* \return Byte array of the header.
	*/
	std::vector<byte> pack();
};

/** A CRC table for fast checksum lookups. */
extern byte crc_sum_Table[256];

/** Create a CRC table for fast checksum lookups. Populate crc_sum_Table */
void generate_crc_table();

/**
 * Footer for message packets
 * |          |          |
 * |:--------:|:--------:|
 * |  01-08   |  09-16   |
 * |checksum 1|checksum 2|
 */
struct MESSAGE_FOOTER 
{ 
	/** checksum bit 1 */
	byte chk1 = 0x00; 
	/** checksum bit 2 */
	byte chk2 = 0x00; 

	MESSAGE_FOOTER() {};
	/**
	 * Generates the CRC footer from the rest of the message.
	 * \param head_and_body Byte array of the rest of the message combined in the proper order.
	 */
	MESSAGE_FOOTER(std::vector<byte> head_and_body);
	/**
	 * Boil the MESSAGE_FOOTER down to an array of bytes that slapped at the end of a MESSAGE and sent across the network. It is mostly just a CRC sum
	 *
	 * \return Byte array of the footer.
	 */
	std::vector<byte> pack();

private:
};

/**
 * Base class for other messages.
 */
class MESSAGE 
{
public:
	/**
	 * Boil the MESSAGE down to an array of bytes that can be padded with a header and footer and shipped on the network.
	 * 
	 * \return Byte array of the message.
	 */
	virtual std::vector<byte> pack() = 0;
	/**
	 * Size of the array of bytes produced by MESSAGE::pack()
	 * 
	 * \return Size of array.
	 */
	virtual size_t size() = 0;
};

/**
 * A packed message waiting for sending
 * |         |       |         |
 * |:-------:|:-----:|:-------:|
 * |  01-24  | 25-n  | n+1-n+16|
 * |  Header |Message|  Footer |
 */
struct PACKED_MESSAGE
{

	PACKED_MESSAGE() {  };

	/**
	 * Constructor that sets a message up by accepting a MESSAGE type.
	 * \param message Message to be the main body of the message sent on the network.
	 */
	PACKED_MESSAGE(MESSAGE* message);

	/**
	 * Return a fully generated byte packet. This is ready to be sent over the network connections.
	 * \return byte packet.
	 */
	std::vector<byte> get_packet();
private:
	/** Header */
	MESSAGE_HEADER header;
	/** Message to pack */
	MESSAGE* message = 0;
	/** Message as a packed string */
	std::vector<byte> packet;
	/** Footer, mainly checksums */
	MESSAGE_FOOTER footer;

	/**
	* Get MESSAGES based on byte 2 of the header.
	* @return The message type of the main body.
	*/
	MESSAGES get_message_enum_by_type();
};

/**
 * A container for adding strings to network messages.
 * |         |       |
 * |:-------:|:-----:|
 * |  01-08  | 09-n  |
 * |  Length |String |
 */
struct Message_String
{
	/** Length of the string */
	byte length;
	/** The string */
	char* str = 0;
	Message_String() { length = 0;}
	/**
	 * String creator
	 * \param string The string to be contained in the container.
	 */
	Message_String(const char* string)
	{
		length = sizeof(string)+1;
		str = (char*) string;
	}
	/**
	 * Boil the string down to an array of bytes.
	 *
	 * \return Byte array of the message.
	 */
	std::vector<byte> pack();
};

#endif // !NETWORK_MESSAGES