# This is a basic workflow to help you get started with Actions

name: Test Coverage

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [patch/**,  feature/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_code_cover_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gcovr
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup testing Network (Linux)
      # Create a testing network called wlan0
      if: runner.os == 'Linux'
      run: |
        docker network create --opt com.docker.network.bridge.name=nat test-net --subnet "192.168.0.0/24"
        ifconfig
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Attempt Permissions fix
      if: runner.os == 'Linux'
      run: |
        cat /proc/bus/input/devices
        echo "**************"
        ls /dev/input
        echo "**************"
        ls /dev/input/by-path

        #sudo +666 /dev/uinput

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake . -DRUN_COVER=true

      
    - name: Run
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: make cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage.xml
        path_to_write_report: ./codecov_report.txt
        verbose: true
