# This is a basic workflow to help you get started with Actions

name: cppcheck-test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ version/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: ArtificialAmateur/clang-tidy-action@0.01
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
