# This is a basic workflow to help you get started with Actions

name: cppcheck-test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ version/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        uses: ArtificialAmateur/cpp-linter-action@0.01
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
