name: Documentation

on:
  push:
    branches:
      documentation

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: "mkdir out"
    - name: Doxygen Action
      # You may pin to the exact commit or the version.
      # uses: mattnotmitt/doxygen-action@9964e41e7f2e2a56e42fe789421f3fe33e938d63
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        doxyfile-path: .github/github_doxy #Errors on warnings
    - run: "ls -a out/documents"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './out/documents/html'
